language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t docker-front ./frontend

script: 
  - docker run -e CI=true -it -p 8080:80 docker-front -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: yourgg
  env: Yourgg-env
  bucket_name: elasticbeanstalk-ap-northeast-2-607275276429
  bucket_path: yourgg
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
