language: generic

services:
  - docker

before_install:
  - echo "dockerfile build starting"

script: 
  - docker-compose up

after_success:
  - echo "docker-compose up"

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: yourgg
  env: Yourgg-env
  bucket_name: elasticbeanstalk-ap-northeast-2-607275276429
  bucket_path: yourgg
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY