version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - "8080:80"
    volumes:
      - /app/node_modules
      - ./frontend:/app

  backend:
    build: 
      dockerfile: Dockerfile.dev
      context: ./backend
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - "3000:3000"  
